meta_product_name: "Petzr"
meta_title: "Petr | The best pet sitter for your pet"
meta_description: "Petzr helps you to find the best pet sitter for your pet"
meta_image: "https://images.unsplash.com/photo-1623387641168-d9803ddd3f35?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2940&q=80" # should exist in `app/assets/images/`
