meta_product_name: "Petzr"
meta_title: "Petr | The best pet sitter for your pet"
meta_description: "Petzr helps you to find the best pet sitter for your pet"
meta_image: "cover.jpeg" # should exist in `app/assets/images/`
